apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  annotations:
    metallb.universe.tf/allow-shared-ip: sharing key
  labels:
    app: influxdb
spec:
  type: ClusterIP
  ports:
    - port: 8086
      name: http
      protocol: TCP
      targetPort: 8086
  selector:
    app: influxdb
  loadBalancerIP: 192.168.49.240

