apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress
spec:
  ports:
    - port: 5050
      targetPort: 80
      protocol: TCP
  selector:
    app: mysql
    tier: wordpress
  type: LoadBalancer
  loadBalancerIP: 192.168.49.241
