apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  annotations:
    metallb.universe.tf/allow-shared-ip: sharing key
  labels:
    app: mysql
spec:
  loadBalancerIP: 192.168.49.240
  type: ClusterIP
  ports:
    - port: 3306
      name: http
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql
