apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.49.242
  selector:
    app: phpmyadmin
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 80
