apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      restartPolicy: Always
	  containers:
      - image: wordpress:latest
        imagePullPolicy: Never
        name: wordpress
        ports:
        - containerPort: 5050
          name: wpport
