apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
        tier: frontend
    spec:
      restartPolicy: Always
      containers:
      - image: ftps:latest
        imagePullPolicy: Never
        name: ftps
        ports:
        - containerPort: 21
        - containerPort: 20
        - containerPort: 30100
        - containerPort: 30101
        - containerPort: 30102
        - containerPort: 30103

