apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
data:
  telegraf.conf: |+
    [agent]
        interval = "5s"
    [[outputs.influxdb]]
      urls = ["influxdb-service:8086"]
      database = "telegraf"
      username = "ljurdant"
      password = "yo"
    [[inputs.docker]]
      endpoint = "unix:///var/run/docker.sock"
      gather_services = false
      container_names = []
      source_tag = false
      container_name_include = []
      container_name_exclude = []
      timeout = "5s"
      perdevice = true
      total = false
      docker_label_include = []
      docker_label_exclude = ["*annotation.kubernetes*"]
