apiVersion: v1
kind: Secret
metadata:
    name: telegraf-secret
type: Opaque
stringData:
    INFLUXDB_DB: grafana
    INFLUXDB_URL: http://influxdb-service:8086
    INFLUXDB_USER: ljurdant
    INFLUXDB_USER_PASSWORD: yo
