apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
spec:
    selector:
        matchLabels:
            app: telegraf
    minReadySeconds: 5
    template:
        metadata:
            labels:
                app: telegraf
        spec:
            containers:
                - image: telegraf:latest
                  name: telegraf
                  envFrom:
                  - secretRef:
                      name: telegraf-secret
                  ports:
                  - containerPort: 8125 
                  volumeMounts:
                      - name: telegraf-config
                        mountPath: /etc/telegraf/telegraf.conf
                        subPath: telegraf.conf
                        readOnly: true
                      - name: docker-socket
                        mountPath: "/var/run/docker.sock"
            volumes:
                - name: telegraf-config
                  configMap:
                    name: telegraf-config
                - name: docker-socket
                  hostPath:
                    path: /var/run/docker.sock
