apiVersion: 1

datasources:
  - name: grafana
    type: influxdb
    access: proxy
    database: grafana
    user: ljurdant
    password: yo
    url: influxdb-service:8086
    jsonData:
      httpMode: GET
